:sparkles: 스터디 채널 자동 생성 봇 구현 중
babiesdev/baby-bot pull request #30
Opened 2023-02-19 12:19 UTC by Mang-Joo

SlashCommand -> 승인 쪽에서 Role 생성과 채널생성을 동시에 하려고 하는데 동시에 진행되지 않아
RoleID를 입력할 수 없어 채널에 역할 제한을 둘 수 없습니다.

2023-02-19 15:57 UTC, gunkim reviewed
일단 1차적으로 코멘트 남겼습니다. 세이프티 콜을 사용하는 부분들이나 불필요한 주석이 제거되면 좋을 것 같아요.

2023-02-19 15:57 UTC, gunkim commented on src/main/kotlin/io/babydevelopers/babybot/application/spring/config/DiscordBotAddListener.kt
> +        if (it is JDA) {
빈이 초기화되는 시점에 JDA일 경우 여러 슬래시 커맨드들을 같이 등록해주는 코드인 것 같은데, 애초에 JDA 빈을 등록하는 코드가 있는데, 그 부분에서 추가해주는 방법이 더 좋지 않을까요? 

코드를 바로 봤을 때 `BeanPostProcessor`을 상속한 `DiscordBotAddListener`가 무슨 역할을 하는지 잘 와닿지 않는 것 같아요.

2023-02-19 15:57 UTC, gunkim commented on src/main/kotlin/io/babydevelopers/babybot/application/spring/mangjoo/controller/SlashCommand.kt
> +            "승인" -> {
event 타입을 정의해볼 수 있지 않을까요? 만약 커맨드가 변경될 경우 이 코드도 영향을 받을 것 같아서요.

2023-02-19 15:57 UTC, gunkim commented on src/main/kotlin/io/babydevelopers/babybot/application/spring/mangjoo/controller/SlashCommand.kt
> +                if (event.member?.hasPermission(ADMINISTRATOR)!!) {
전체적으로 코드가 세이프티 콜을 사용하는 경우가 많은 것 같은데, 이 코드들을 해결해보면 좋을 것 같아요.

2023-02-19 15:57 UTC, gunkim commented on src/main/kotlin/io/babydevelopers/babybot/application/spring/mangjoo/service/AutoForumListener.kt
> +            .voiceChannels.stream()
코틀린에서는 `.stream()`은 없어도 돼요!

2023-02-19 15:57 UTC, gunkim commented on src/main/kotlin/io/babydevelopers/babybot/application/spring/mangjoo/service/ManualForumListener.kt
> +            throw IllegalArgumentException("게시판을 통해서 승인을 해야합니다.")
kotlin에서 제공해주는 `require` 함수를 쓰면 예외 처리가 더 깔끔해집니다!

2023-02-22 13:27 UTC, gunkim requested changes

2023-02-22 13:27 UTC, gunkim commented on src/main/kotlin/io/babydevelopers/babybot/application/spring/mangjoo/service/AutoForumListener.kt
> +package io.babydevelopers.babybot.application.spring.mangjoo.service
얘는 패키지가 discord 밑으로 들어와야 할 것 같네요. mangjoo는 제거하구요.

2023-02-22 13:27 UTC, gunkim commented on src/main/kotlin/io/babydevelopers/babybot/application/spring/discord/service/ManualForumListener.kt
> +        require(isForum(event.channel)) { throw IllegalStateException("게시판을 통해서 승인을 해야합니다.") }
예외는 제거하고 문자열만 지정해주면 됩니다. `IllegalStateException`를 사용하려는 목적이면 `error` 함수를 쓰는게 더 적합한 것 같아요!

2023-02-22 13:27 UTC, gunkim commented on src/main/kotlin/io/babydevelopers/babybot/application/spring/discord/service/ManualForumListener.kt
> +        discordServer.deleteAllRoles(channelName)
deleteAllRoles와 deleteChannel는 같이 이루어져야 하는 작업이니 둘을 확장 함수로 묶는건 어떨까요?
그리고 channelName 밑에 줄바꿈이 하나 들어가면 더 가독성이 좋을 것 같아요.
예를 들어
```kt
discordServer.apply {
    deleteAllRoles~~
    deleteChannel~~
}
```

2023-02-22 13:27 UTC, gunkim commented on src/main/kotlin/io/babydevelopers/babybot/application/spring/discord/service/ManualForumListener.kt
> +        val discordServer = DiscordServer(event)
여기 밑에도 줄바꿈이 하나 들어가면 이쁠 것 같아요.

2023-02-22 13:27 UTC, gunkim commented on src/main/kotlin/io/babydevelopers/babybot/application/spring/config/DiscordBotConfig.kt
> +        .also { it.addEventListener(slashCommand) }
이 코드는 JDA가 build()된 후 확장함수로 처리를 안하고 위로 올라가는 게 좋을 것 같아요.

2023-02-22 13:27 UTC, gunkim commented on src/main/kotlin/io/babydevelopers/babybot/application/spring/discord/controller/SlashCommand.kt
> +                .also { event.reply("${event.member?.effectiveName}님이 ${event.channel.name}에 참여하였습니다.").queue() }
이 코드는 확장 함수를 사용 안하는게 오히려 가독성이 좋을 것 같아요. createChannel 같은 경우는 사용을 안하셨는데, 일관성 측면에서도요.

2023-02-22 13:27 UTC, gunkim commented on src/main/kotlin/io/babydevelopers/babybot/application/spring/discord/domain/DiscordServer.kt
> +    fun getRole(channelName: String) = guild.getRolesByName(channelName, true)[0]!!
이 코드는 NPE 발생의 여지가 있을 것 같은데, null이 아닌게 확실한건가요?

2023-02-22 13:27 UTC, gunkim commented on src/main/kotlin/io/babydevelopers/babybot/application/spring/discord/domain/Permission.kt
> +        event.member?.hasPermission(Permission.ADMINISTRATOR)!!,
이 코드도 NPE 여지가 있을 것 같아요. 되도록이면 safety call은 자제를 하는게 좋을 것 같아요.

2023-02-22 13:56 UTC, gunkim requested changes

2023-02-22 13:56 UTC, gunkim commented on src/main/kotlin/io/babydevelopers/babybot/application/spring/discord/service/ManualForumListener.kt
> +                .let { role -> discordServer.addRoleToMember(event.member!!, role) }
요기두 널!!

2023-02-23 13:13 UTC, gunkim approved these changes

2023-02-23 13:27 UTC, Junnyjun approved these changes

2023-02-23 15:47 UTC, merged